//$file${.::main.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: ColourDiffusal.qm
// File:  ${.::main.c}
//
// This code has been generated by QM 5.3.0 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open source software: you can redistribute it under
// the terms of the GNU General Public License as published by the Free
// Software Foundation.
//
// This code is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
// more details.
//
// NOTE:
// Alternatively, this generated code may be distributed under the terms
// of Quantum Leaps commercial licenses, which expressly supersede the GNU
// General Public License and are specifically designed for licensees
// interested in retaining the proprietary status of their code.
//
// Contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::main.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "qpc.h"    /* QP/C framework API */
#include "app.h"    /* Board Support Package interface */
#include "central.h"
#include "bsp_system.h"
#include "bsp_gpio.h"
#include "bsp_i2c.h"
#ifdef DEBUG_CFG
#include <stdio.h>
#endif
#include <stdbool.h>
#include "includes.h"
#include "sdd1306.h"
#include "veml6040.h"
#include "sdd1306_font.h"
/*---------------------------------------------------------------------------*/

Q_DEFINE_THIS_FILE

/* the main function -------------------------------------------------------*/
int main() {

    /* initialize the framework */
    QF_init(); //Same as OSInit();

    static QEvt const *central_queueSto[100]; /* event queue buffer for Central */
    static OS_STK centralStack[512];

    static QF_MPOOL_EL(QEvt) smlPoolSto[25];
		QF_poolInit(smlPoolSto, sizeof(smlPoolSto), sizeof(smlPoolSto[0]));

    /* initialize the BSP and Peripherals */
    bsp_system_init();
    bsp_gpio_user_key_init();
    bsp_gpio_PB0_init();
    bsp_gpio_PB1_init();
    bsp_gpio_PB10_init();
    bsp_i2c_init();
    veml6040_init();
    sdd1306_init();

    /* instantiate and start the Blinky active object */
    Central_ctor(); /* in C you must explicitly call the Central constructor */
    QACTIVE_START(AO_Central, /* active object to start */
            1U,                  /* priority of the active object */
            central_queueSto,     /* event queue buffer */
            Q_DIM(central_queueSto), /* the length of the buffer */
            centralStack, sizeof(centralStack),       /* task stack */
            (void *)0);          /* initialization event (not used) */
#ifdef DEBUG_CFG
	printf("main: started\n");
#endif
    return QF_run(); //Same as OSStart() /* let the framework run the application */

}

bool DebounceSwitch()
{
    static uint16_t State = 0; // Current debounce status
    State=(State<<1) | !bsp_gpio_user_key_get_state() | 0xe000;
    if(State==0xf000)return true;
    return false;
}

bool DebounceSwitch2(){
    static uint16_t State = 0; // Current debounce status
    State=(State<<1) | !bsp_gpio_PB1_get_state() | 0xe000;
    if(State==0xf000)return true;
    return false;
}

bool DebounceSwitch3(){
    static uint16_t State = 0; // Current debounce status
    State=(State<<1) | !bsp_gpio_PB0_get_state() | 0xe000;
    if(State==0xf000)return true;
    return false;
}

#if OS_TIME_TICK_HOOK_EN > 0
void  App_TimeTickHook (void)
{
    QTIMEEVT_TICK_X(0U, &l_tickHook); // time events at rate 0
    if(DebounceSwitch()){
        //ChangeMode = true;
        const QEvt *pe = Q_NEW(QEvt, SWITCHMODE_SIG);
        QACTIVE_POST(AO_Central,pe,((void*)0));
    }
    if(DebounceSwitch2()){
        //OSSemPost(pa6switchSem);
        const QEvt *pe = Q_NEW(QEvt, LEDTOGGLE_SIG);
        QACTIVE_POST(AO_Central,pe,((void*)0));
    }
    if(DebounceSwitch3()){
        //OSSemPost(pa6switchSem);
        const QEvt *pe = Q_NEW(QEvt, PAUSE_SIG);
        QACTIVE_POST(AO_Central,pe,((void*)0));
    }
}
#endif
